services:

  neox-node:
    container_name: bridge-devnet-neox
    build:
      context: ./go-ethereum
      dockerfile: ../neox.Dockerfile
    ports:
      - 8562:8562
    command: [ "sh", "-c", "make RESTRICTED_NETWORK=0.0.0.0/0 privnet_start && tail -F ./privnet/single/node1/geth_node.log" ]

  neox-funding:
    container_name: bridge-devnet-neox-funding
    image: node:20
    depends_on:
      - neox-node
      - neon3-node
    volumes:
      - ./tools:/app/tools
      - ./go-ethereum:/app/go-ethereum
    working_dir: /app/tools/neox-funding
    environment:
      - NEOX_RPC_URL=http://neox-node:8562
    command: [
      "sh", "-c",
      "npm install && node fund-neox-accounts.js"
    ]
    restart: "no"

  deploy-neox-message-bridge:
    container_name: bridge-devnet-deploy-neox-message-bridge
    image: node:20
    depends_on:
      - neox-funding
    volumes:
      - ./bridge-evm-contracts:/app
      - ./tools/neox-funding/neox-wallets:/app/wallets
    working_dir: /app
    environment:
      - NEOX_RPC_URL=http://neox-node:8562
    command: >
      sh -c "rm -rf /app/.openzeppelin &&
             npm install &&
             npx hardhat vars set NEOX_DEVNET_RPC_URL $$NEOX_RPC_URL &&
             npx hardhat run scripts/deployMessageBridge.ts --network neoxDevnet"
    restart: "no"

  neon3-node:
    container_name: bridge-devnet-neon3
    image: ghcr.io/axlabs/neo3-privatenet-docker/neo-cli-with-plugins:neo-node-3.8.2
    ports:
      - 40332:40332
    volumes:
      - ./neon3-config/config-consensus.privatenet3.json:/neo-cli/config.json:ro
      - ./neon3-config/wallet-consensus.privatenet3.json:/neo-cli/wallet.json:ro
      - ./neon3-config/rpcserver.config-consensus.json:/neo-cli/Plugins/RpcServer/RpcServer.json:ro
      - ./neon3-config/dbft.config-consensus.json:/neo-cli/Plugins/DBFTPlugin/DBFTPlugin.json:ro
      - ./neon3-config/applicationlogs.config-consensus.json:/neo-cli/Plugins/ApplicationLogs/ApplicationLogs.json:ro
      - ./neon3-config/tokentracker.config-consensus.json:/neo-cli/Plugins/TokensTracker/TokensTracker.json:ro
    entrypoint: [
      "sh", "-c",
      "screen -dmS neo-node dotnet neo-cli.dll && sleep 5 && tail -f ./Logs/ConsensusService/*"
    ]

  neon3-funding:
    container_name: bridge-devnet-neon3-funding
    build:
      dockerfile_inline: |
        FROM ubuntu:24.04
        RUN apt-get update && apt-get install -y curl jq
    depends_on:
      - neon3-node
    volumes:
      - ./tools/neon3-funding/:/root/neon3-funding
      - ./tools/neon3-wallets:/root/neon3-wallets
    environment:
      - NEON3_RPC_URL=http://neon3-node:40332
      - GAS_AMOUNT=10000000
      - GAS_TOKEN_HASH=0xd2a4cff31913016155e38e474a2c06d08be276cf
      - FUNDED_ADDRESS=NYCtX5TPmCyLJSNATAufWfTgMoCit24QQr
    working_dir: /root/neon3-funding
    command: [
      "sh", "-c", 
      "echo \"Funding accounts...\" \
        && chmod u+x neon3-funding.sh \
        && ./neon3-funding.sh $$FUNDED_ADDRESS $$GAS_AMOUNT \
        echo \"Funding complete.\"
      "
      ]

  #  RabbitMQ Management UI: http://localhost:15672 (login: admin/admin123)
  #  RabbitMQ AMQP: amqp://admin:admin123@localhost:5672
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: bridge-devnet-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
#    healthcheck:
#      test: ["CMD", "rabbitmq-diagnostics", "ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#      start_period: 30s

volumes:
  rabbitmq_data:
